name: .NET

trigger:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Lint
    steps:
      - task: UseDotNet@2
        displayName: Setup .NET
        inputs:
          version: 6.0.x
      - script: dotnet restore
        displayName: Restore dependencies
  
  - job: Test
    steps:
      - script: dotnet test --no-build --verbosity normal
        displayName: Test
  
  - job: Build
    steps:
      - script: dotnet build
        displayName: Build
  
  - job: Deploy
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: docker.io
      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          repository: xgepic/weather-api
          tags: latest