name: .NET

trigger:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Lint
    steps:
      - task: BuildQualityChecks@8
        displayName: 'Check build quality'
        inputs:
          checkWarnings: true
          warningFailOption: 'fixed'
          warningFilters: ''
          warningTaskFilters: '/^((vs|ms)build|ant(\\s+.+)?|gradle(w)?(\s+.+)?|grunt|gulp|maven(\s+.+)?|xamarin(android|ios)|xcode(\s+.+)?|cmake|build\s+.+)$/i'
          warningThreshold: '0'
  
  - job: Test
    steps:
      - script: dotnet test --no-build --verbosity normal
        displayName: Test
  
  - job: Build
    steps:
      - script: dotnet build
        displayName: Build
  
  - job: Deploy
    steps:
      - task: Docker@2
        displayName: Build and Push
        inputs:
          containerRegistry: 'DockerHubConnection'
          repository: 'xgepic/weather-api'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: latest