name: .NET

trigger:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Lint
    jobs:
      - job: Lint
        steps:
          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: 'build' 
          - task: BuildQualityChecks@8
            displayName: Check build quality
            inputs:
              checkWarnings: true
              warningThreshold: '0'

  - stage: Test
    jobs:
      - job: Test
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'

  - stage: Build
    jobs: 
      - job: Build
        steps: 
          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: 'build' 

  - stage: DeployStage 
    jobs:
      - job: Deploy
        steps:
        - task: Docker@2
          displayName: deploy
          inputs:
            containerRegistry: 'DockerHubConnection'
            repository: 'xgepic/weather-api'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: latest