name: .NET

trigger:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Test
    steps:
      - script: dotnet test --no-build --verbosity normal
        displayName: Test
  
  - job: LintandBuild
    steps:
      - script: dotnet build
        displayName: Build
      - task: BuildQualityChecks@8
        inputs:
          checkWarnings: true
          warningThreshold: '0'
  
  - job: Deploy
    steps:
      - task: Docker@2
        displayName: deploy
        inputs:
          containerRegistry: 'DockerHubConnection'
          repository: 'xgepic/weather-api'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: latest